name: census-parser
services: 
  frontend: 
    container_name: census-parser-frontend
    image: cmsommerville/census-parser-frontend:latest
    build: 
      context: ./frontend
    ports: 
      - 80:8080
    depends_on:
      - api
  api:
    container_name: census-parser-api
    image: cmsommerville/census-parser-api:latest
    build: 
      context: ./api
    ports:
      - "5002:5000"
    env_file: 
      - api/.env
    volumes: 
      - ./api:/api