name: census-parser
services: 
  frontend: 
    container_name: census-parser-frontend
    image: ghcr.io/cmsommerville/census-parser-frontend:latest
    build: 
      context: ./frontend
    ports: 
      - 80:8080
    depends_on:
      - api
  api:
    container_name: census-parser-api
    image: ghcr.io/cmsommerville/census-parser-api:latest
    environment:
      - DATABASE_URI=sqlite:///api.db
    build: 
      context: ./api
    ports:
      - 5002:5000
    volumes: 
      - ./api:/api